### ISSUE TITLE
connect gui with usb rs232 pl2303

### ISSUE THREAD

**Issue by GoogleCodeExporter** [happyhappysundays/nextcopterplus#3]
```
hi, i'm trying to connect the kk board with rs232 inteface, so i connect tx to 
miso, rx to pin 30, gnd to gnd and 5v to usb 5v, i see the com port but the gui 
didn't show any data.. what speed i must set on the rs232 port? 9600bps is 
defoult. thanks a lot

```

Original issue reported on code.google.com by `daniele....@gmail.com` on 11 Sep 2013 at 1:26

**Comment by happyhappysundays** [comment]
Hi, I know this is a very old request, but if you're interested there is a GUI for OpenAeroVTOL now. It uses the existing programmer, not a new serial port, but works well.
