### ISSUE TITLE
Feature Request - Support flaps or other functions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [happyhappysundays/nextcopterplus#4]
```
Allow switching camera stablization off but still allow output for flaps or 
bomb drop, etc.  Would need a screen to map the extra channels to the output 
M2-M4.

```

Original issue reported on code.google.com by `jgre...@gmail.com` on 12 Mar 2014 at 6:47

**Comment by happyhappysundays** [comment]
Hi - only just saw this a year after it was posted. Sorry - I don't seem to get notifications from GitHub. The actual project (there are many) is not specified but what you ask is already supported in OpenAeroVTOL.
